version: 0.2
env: 
  parameter-store: 
    MONGO_URL: "/vivek/mongouri"
phases:
  pre_build:
    commands:
       - sed -i 's/mongodb_url/'$MONGO_URL'/' app.js
       - echo Build Started on `date`
  build:
    commands:
       - npm install
  post_build:
    commands:
       - echo Build Completed on `date`

artifacts:
  files:
    - '**/*'
