version: 0.2

run-as: root

env:
    parameter-store:
        MONGODB_URL: "/ashutosh/mern/mongodb_ip"
        PORT: "/ashutosh/mern/port"

phases:
    
    # Nothing to install 
    install:
        commands:
            - echo "Installed Packages!!!"
           
            

    # Changing configuration in pre-build phase
    pre_build:
        commands:
            - echo MONGODB_URI=$MONGODB_URL > .env
            - echo PORT=$PORT >> .env

    # Nothing to build
    build:
        commands:
            - echo "Build Done!!!"
            - sudo npm install
#             - sudo npm  install pm2@latest -g
           

    # Nothing for post build, just testing the service
    post_build:
        commands:
            - echo "Post-Build Done!!!"

# Copy all file in current repo to artifact - S3
artifacts:
        files:
           - '**/*'
