version: 0.2
env: 
  parameter-store: 
    MONGO_URL: "/vivek/mongouri"
phases:
 # install:
  #  -nodejs: 12  
    
  pre_build:
    commands:
       - echo MONGODB_URI=$MONGO_URL > .env
       - echo PORT=3000 >> .env
       - echo Build Started on `date`
  build:
    commands:
       - npm install
       - npm install pm2 -g
  post_build:
    commands:
       - echo Build Completed on `date`

artifacts:
  files:
    - '**/*'
